FROM python:3.12-slim AS builder

WORKDIR /app

# install the system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends build-essential \
  rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install -r --no-cache-dir --prefix=/install requirements.txt 

FROM python:3.12-slim

ENV USER=dev

WORKDIR /app

COPY --from=builder /install /usr/local

COPY . .

RUN useradd -m $USER
USER $USER

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]
