---
nginx_packages:
  - nginx
  - python3
  - python3-pip
  - openssl
nginx_service: nginx
nginx_domain: ubuntulab
nginx_ssl_cert: /etc/nginx/ssl/ubuntulab.crt
nginx_ssl_key: /etc/nginx/ssl/ubuntulab.key