pipeline{
  agent any

  options {
    timestamps()
    ansiColor('xterm')
    buildDiscarder(logRotator(numToKeepStr: '10'))

  }

  parameters {
    choice (
      name: 'Environment',
      choices: ['dev', 'stage', 'prod'],
      description: 'Target Environment'
    )
  }

  environment {
    VENV = "${WORKSPACE}/venv"
    ANSIBLE_HOST_KEY_CHECKING = "False"
    PROJECT_DIR = "ansible/projects/web-server"
  }

  stages{
    stage("Git Checkout"){
      steps{
        git branch: "main",
        url: "https://github.com/eswarmaganti/devops-interview-prep.git"
      }
    }
    stage("Setup Python Environment"){
      steps{
        sh '''
        python3 -m venv $VENV
        source "$VENV/bin/activate"
        pip install --upgrade pip
        pip install ansible ansible-lint yamllint

        '''
      }
    }
    stage("Install Ansible Galaxy Roles"){
      steps{
        sh '''
        source "$VENV/bin/activate"
        ansible-galaxy install -r "${WORKSPACE}/${PROJECT_DIR}/requirements.yaml" || true
        '''
      }
    }
    stage("YAML Lint Check"){
      steps {
        sh '''
        source "$VENV/bin/activate"
        cd "${WORKSPACE}/${PROJECT_DIR}"
        yamllint .
        '''
      }
    }

    stage("Ansible Lint Check"){
      steps {
        sh '''
          source "$VENV/bin/activate"
          cd "${WORKSPACE}/${PROJECT_DIR}"
          ansible-lint
        '''
      }
    }
  
    stage("Ansible Syntax Check"){
      steps{
        sh '''
          source "$VENV/bin/activate"
          ansible-playbook "${WORKSPACE}/${PROJECT_DIR}/playbook.yaml" \
          -i "${WORKSPACE}/${PROJECT_DIR}/inventory/${Environment}.yaml" \
          --syntax-check
        '''
      }
    }

    stage('Dry Run') {
      steps {
        sshagent(credentials: ['vagrant-ssh-key']){
          sh '''
            source "$VENV/bin/activate"
            ansible-playbook "${WORKSPACE}/${PROJECT_DIR}/playbook.yaml" \
            -i "${WORKSPACE}/${PROJECT_DIR}/inventory/${Environment}.yaml" \
            --check --diff
          '''
          }
      }
    }
  }
}