---
galaxy_info:
  author: Maganti Eswar Krishna
  description: DevOps Engineer
  company: NA
  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: "2.2"

  galaxy_tags: []
dependencies: []
  