---
all:
  vars:
    ansible_user: ansible
    ansible_become: true
    ansible_become_method: sudo
  children:
    lab:
      hosts:
        ansiblevagrantlab01:
          ansible_host: 192.168.58.101
